/* Sample leads (fictional) for the new-lead email tests and scripts/preview-lead-email.ts. */
export const BLOB = 'https://abc123.public.blob.vercel-storage.com'

export const SAMPLE_LEADS: Record<string, Record<string, any>> = {
  quote: {
    id: 742,
    sourceForm: 'quote-request',
    name: 'Jordan Ellis',
    company: 'Gulf Coast Rendering Co.',
    email: 'jordan.ellis@example.com',
    phone: '(281) 555-0142',
    message: 'Equipment: Decanter\n…composed summary…',
    payload: {
      formType: 'request_quote',
      name: 'Jordan Ellis',
      company: 'Gulf Coast Rendering Co.',
      email: 'jordan.ellis@example.com',
      phone: '(281) 555-0142',
      location: 'Baytown, TX',
      equipment: 'decanter',
      brand: 'alfa-laval',
      model: 'NX 4500',
      serviceNeeded: 'Full rebuild, bowl balancing',
      urgency: 'this-week',
      message: "Bowl is vibrating above 0.4 in/s since last week's shutdown.\n\nPhotos attached of the scroll & the bearing housing <see below>.",
      pageSource: '/services/decanter-centrifuge-repair/',
      photoCount: 2,
      photoIds: [11, 12],
      photoUrls: [
        { url: `${BLOB}/scroll-flights-a1b2c3d4e5.jpg`, thumb: `${BLOB}/scroll-flights-a1b2c3d4e5-400x300.jpg`, name: 'scroll-flights.jpg', size: 943718 },
        { url: `${BLOB}/bearing-housing-f6a7b8c9d0.jpg`, thumb: `${BLOB}/bearing-housing-f6a7b8c9d0-400x300.jpg`, name: 'bearing-housing.jpg', size: 412000 },
      ],
      'cf-turnstile-response': 'tok',
      contact_time: '',
    },
  },
  emergency: {
    id: 743,
    sourceForm: 'emergency',
    name: 'Sam Ortega',
    company: 'Midwest Starch Processing',
    phone: '708-555-0199',
    payload: {
      formType: 'emergency_service',
      name: 'Sam Ortega',
      company: 'Midwest Starch Processing',
      phone: '708-555-0199',
      equipment: 'disc-stack',
      urgency: 'emergency',
      whatHappened: "Separator tripped on high vibration at 11:15 PM and won't restart.\nLine 2 is down.",
      pageSource: '/emergency-centrifuge-repair/',
      photoCount: 0,
      photoIds: [],
      photoUrls: [],
    },
  },
  machine: {
    id: 744,
    sourceForm: 'quote-request',
    name: 'Priya Raman',
    company: 'Lakeshore Biofuels',
    email: 'p.raman@example.com',
    phone: '219-555-0177',
    payload: {
      formType: 'request_quote',
      equipment: 'decanter',
      brand: 'andritz',
      urgency: 'planning',
      message: 'Interested in this unit for a Q1 install.\nCan you confirm lead time?',
      pageSource: '/inventory/sample-decanter/',
      machine: { inventoryId: 'INV-0000', title: 'Sample decanter listing', url: 'https://centrifuge.com/inventory/sample-decanter/', specsSnapshot: [{ label: 'Material', value: 'Stainless' }] },
      photoUrls: [],
    },
  },
  manual: { id: 745, sourceForm: 'phone-in', name: 'Walk-in caller', phone: '555-0100', message: 'Called about a gearbox.\nWants a callback.' },
}

export const CTX = {
  siteUrl: 'https://centrifuge.com',
  emergencyDisplay: '832-338-4990',
  hoursDisplay: 'Mon–Fri: 6:00 AM – 6:00 PM',
  oncallDisplay: 'On-Call 24/7',
  recipientNames: ['Mark', 'Ron', 'David', 'Cynthia'],
  now: new Date('2026-10-01T19:14:00Z'),
}
