/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    'oem-brands': OemBrand;
    industries: Industry;
    locations: Location;
    posts: Post;
    'case-studies': CaseStudy;
    'how-it-works': HowItWork;
    inventory: Inventory;
    'competitor-snapshots': CompetitorSnapshot;
    faqs: Faq;
    media: Media;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'oem-brands': OemBrandsSelect<false> | OemBrandsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'how-it-works': HowItWorksSelect<false> | HowItWorksSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    'competitor-snapshots': CompetitorSnapshotsSelect<false> | CompetitorSnapshotsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'header-nav': HeaderNav;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-nav': HeaderNavSelect<false> | HeaderNavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text — required for accessibility & SEO.
   */
  alt: string;
  /**
   * Optional caption; include model numbers where known.
   */
  caption?: string | null;
  /**
   * PDF Studio annotation overlay objects.
   */
  pdfAnnotations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  /**
   * Page H1 (defaults to title).
   */
  h1?: string | null;
  /**
   * Which lead form embeds on this page.
   */
  formType?: ('request_quote' | 'emergency_service' | 'free_inspection' | 'contact' | 'send_photos') | null;
  /**
   * AEO question (data/faq-bank.md).
   */
  answerBoxQuestion?: string | null;
  /**
   * 40–60 word direct answer under the H1.
   */
  answerBox?: string | null;
  /**
   * Lead paragraph after the answer box.
   */
  intro?: string | null;
  capabilitiesHeading?: string | null;
  capabilities?:
    | {
        item: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  processHeading?: string | null;
  process?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedServices?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedBrands?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedIndustries?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional long-form body (not rendered by the block template).
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Use the safety-red emergency hero treatment.
   */
  emergencyVariant?: boolean | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oem-brands".
 */
export interface OemBrand {
  id: number;
  /**
   * Corrected canonical spelling only (never legacy).
   */
  name: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  featured?: boolean | null;
  /**
   * If set, this brand 301-redirects to /brands/<slug>.
   */
  mergeInto?: string | null;
  /**
   * 40–60 word direct answer under the H1 (AEO).
   */
  answerBox?: string | null;
  /**
   * Hero subtitle / lead paragraph.
   */
  intro?: string | null;
  /**
   * Independent-service disclosure line (legally clean positioning).
   */
  disclosure?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  modelsServiced?:
    | {
        model: string;
        id?: string | null;
      }[]
    | null;
  typesServiced?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  capabilities?:
    | {
        item: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        /**
         * Image URL (e.g. an S3 URL).
         */
        url: string;
        alt: string;
        id?: string | null;
      }[]
    | null;
  relatedServices?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedBrands?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedIndustries?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  /**
   * 40–60 word direct answer under the H1 (AEO).
   */
  answerBox?: string | null;
  intro?: string | null;
  hero?: {
    /**
     * Hero image URL (S3).
     */
    url?: string | null;
    alt?: string | null;
  };
  typicalEquipment?:
    | {
        text: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  failureModes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  relevantServices?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedBrands?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  label: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  streetAddress: string;
  addressLocality: string;
  addressRegion: string;
  postalCode: string;
  /**
   * nap.json phone role key.
   */
  phoneRole?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  excerpt?: string | null;
  hero?: {
    url?: string | null;
    alt?: string | null;
  };
  sections?:
    | {
        heading: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  internalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  /**
   * e.g. "Confidential rendering client" — no real names without written permission.
   */
  clientIndustry?: string | null;
  machineBrandModel?: string | null;
  hero?: {
    url?: string | null;
    alt?: string | null;
  };
  problem?: string | null;
  scopeItems?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  beforeAfterUrls?:
    | {
        beforeUrl: string;
        beforeAlt?: string | null;
        afterUrl: string;
        afterAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        /**
         * Image URL (e.g. an S3 URL).
         */
        url: string;
        alt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * TODO(verify) until client confirms.
   */
  timeline?: string | null;
  /**
   * TODO(verify) until client confirms.
   */
  outcome?: string | null;
  relatedServices?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedBrands?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  scopeOfWork?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  beforeAfter?:
    | {
        before?: (number | null) | Media;
        after?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works".
 */
export interface HowItWork {
  id: number;
  title: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  /**
   * 40–60 word direct answer under the H1 (AEO).
   */
  answerBox?: string | null;
  sections?:
    | {
        heading: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  signsNeedRepair?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube video ID (optional).
   */
  videoId?: string | null;
  relatedService?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedBrands?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: number;
  /**
   * e.g. "Sharples P-3000 Solid-Bowl Decanter Centrifuge".
   */
  title: string;
  /**
   * URL segment. Auto-generated from the title if left blank.
   */
  slug: string;
  /**
   * OEM brand, e.g. Sharples (must match /data/oem-brands.json spelling).
   */
  brand?: string | null;
  machineType: 'decanter' | 'basket' | 'disc-stack' | 'pusher' | 'peeler' | 'separator' | 'other';
  model?: string | null;
  condition?: ('reconditioned' | 'rebuilt' | 'used' | 'for-parts') | null;
  /**
   * Sold items are hidden from the public site.
   */
  availability?: ('available' | 'sale-pending' | 'sold') | null;
  /**
   * USD. Leave blank and check "Price on request" if not public.
   */
  price?: number | null;
  priceOnRequest?: boolean | null;
  /**
   * 1–2 sentences shown on the listing card.
   */
  shortDescription?: string | null;
  /**
   * Full description shown on the detail page.
   */
  description?: string | null;
  /**
   * Bowl diameter, max RPM/G-force, material, drive, etc.
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload a photo, or paste an image URL (e.g. an S3 URL).
   */
  images?:
    | {
        /**
         * Upload, or use the URL field.
         */
        image?: (number | null) | Media;
        /**
         * Image URL if not uploading.
         */
        imageUrl?: string | null;
        /**
         * Describe the photo (used when pasting a URL).
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show first in listings.
   */
  featured?: boolean | null;
  /**
   * Search metadata. Title ≤60, description ≤155 characters.
   */
  seo?: {
    /**
     * Unique <title>, ≤60 chars. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Meta description, ≤155 chars.
     */
    description?: string | null;
    /**
     * Only if this page should canonicalize to a different URL.
     */
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitor-snapshots".
 */
export interface CompetitorSnapshot {
  id: number;
  /**
   * Display name, e.g. "Acme Centrifuge Co."
   */
  label: string;
  domain: string;
  /**
   * When this snapshot was captured (from the export).
   */
  capturedAt: string;
  /**
   * SEO visibility score 0–100.
   */
  visibility?: number | null;
  /**
   * Count of top-10 ranking keywords.
   */
  topKeywords?: number | null;
  /**
   * Estimated monthly organic traffic.
   */
  estTraffic?: number | null;
  /**
   * Visibility change vs. prior snapshot.
   */
  delta?: number | null;
  /**
   * Placeholder/demo data — replace via CSV import.
   */
  isExample?: boolean | null;
  keywords?:
    | {
        query: string;
        ourRank?: number | null;
        theirBest?: number | null;
        /**
         * Rank change (+ improved, − dropped).
         */
        movement?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?:
    ('repair-rebuilds' | 'emergency-field' | 'parts-fabrication' | 'buying-selling' | 'costs-turnaround') | null;
  /**
   * Path to the deep page this answer links to.
   */
  deepLink?: string | null;
  /**
   * Sort order within the category.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  type: 'request_quote' | 'emergency_service' | 'free_inspection' | 'sell_centrifuge' | 'contact' | 'send_photos';
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  pageSource?: string | null;
  /**
   * Captured UTM params.
   */
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Full submitted field set.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * CRM pipeline stage.
   */
  pipelineStage?: ('new' | 'contacted' | 'quoted' | 'won' | 'lost') | null;
  /**
   * Estimated deal value (USD).
   */
  estimatedValue?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Legacy path, e.g. /sharples/
   */
  from: string;
  /**
   * Target path, e.g. /brands/sharples/
   */
  to: string;
  type?: ('301' | '302') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Profile photo (image, ≤2 MB — square-cropped on upload).
   */
  avatar?: (number | null) | Media;
  role: 'super-admin' | 'editor' | 'content-manager' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'oem-brands';
        value: number | OemBrand;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'how-it-works';
        value: number | HowItWork;
      } | null)
    | ({
        relationTo: 'inventory';
        value: number | Inventory;
      } | null)
    | ({
        relationTo: 'competitor-snapshots';
        value: number | CompetitorSnapshot;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  h1?: T;
  formType?: T;
  answerBoxQuestion?: T;
  answerBox?: T;
  intro?: T;
  capabilitiesHeading?: T;
  capabilities?:
    | T
    | {
        item?: T;
        detail?: T;
        id?: T;
      };
  processHeading?: T;
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedServices?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedBrands?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedIndustries?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  body?: T;
  emergencyVariant?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oem-brands_select".
 */
export interface OemBrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  featured?: T;
  mergeInto?: T;
  answerBox?: T;
  intro?: T;
  disclosure?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  modelsServiced?:
    | T
    | {
        model?: T;
        id?: T;
      };
  typesServiced?:
    | T
    | {
        value?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        item?: T;
        detail?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  images?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  relatedServices?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedBrands?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedIndustries?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  answerBox?: T;
  intro?: T;
  hero?:
    | T
    | {
        url?: T;
        alt?: T;
      };
  typicalEquipment?:
    | T
    | {
        text?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  failureModes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  relevantServices?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedBrands?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  streetAddress?: T;
  addressLocality?: T;
  addressRegion?: T;
  postalCode?: T;
  phoneRole?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  hero?:
    | T
    | {
        url?: T;
        alt?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  internalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  publishedAt?: T;
  heroImage?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  clientIndustry?: T;
  machineBrandModel?: T;
  hero?:
    | T
    | {
        url?: T;
        alt?: T;
      };
  problem?: T;
  scopeItems?:
    | T
    | {
        value?: T;
        id?: T;
      };
  beforeAfterUrls?:
    | T
    | {
        beforeUrl?: T;
        beforeAlt?: T;
        afterUrl?: T;
        afterAlt?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  timeline?: T;
  outcome?: T;
  relatedServices?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedBrands?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  scopeOfWork?: T;
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works_select".
 */
export interface HowItWorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  answerBox?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  signsNeedRepair?:
    | T
    | {
        value?: T;
        id?: T;
      };
  videoId?: T;
  relatedService?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedBrands?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  brand?: T;
  machineType?: T;
  model?: T;
  condition?: T;
  availability?: T;
  price?: T;
  priceOnRequest?: T;
  shortDescription?: T;
  description?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        alt?: T;
        id?: T;
      };
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitor-snapshots_select".
 */
export interface CompetitorSnapshotsSelect<T extends boolean = true> {
  label?: T;
  domain?: T;
  capturedAt?: T;
  visibility?: T;
  topKeywords?: T;
  estTraffic?: T;
  delta?: T;
  isExample?: T;
  keywords?:
    | T
    | {
        query?: T;
        ourRank?: T;
        theirBest?: T;
        movement?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  deepLink?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  pdfAnnotations?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        avatar?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  pageSource?: T;
  utm?: T;
  payload?: T;
  pipelineStage?: T;
  estimatedValue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  foundingYear?: number | null;
  /**
   * TODO(verify) — see nap.json.
   */
  publicEmail?: string | null;
  trustBar?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Exact social profile URLs — TODO(verify) in Cycle 4.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav".
 */
export interface HeaderNav {
  id: number;
  /**
   * Header/megamenu structure (seeded from data/navigation.json).
   */
  structure?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer column structure (seeded from data/navigation.json).
   */
  structure?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  foundingYear?: T;
  publicEmail?: T;
  trustBar?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  structure?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  structure?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'oem-brands';
          value: number | OemBrand;
        } | null)
      | ({
          relationTo: 'industries';
          value: number | Industry;
        } | null)
      | ({
          relationTo: 'locations';
          value: number | Location;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'how-it-works';
          value: number | HowItWork;
        } | null)
      | ({
          relationTo: 'inventory';
          value: number | Inventory;
        } | null)
      | ({
          relationTo: 'faqs';
          value: number | Faq;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}